spring.application.name=faq
server.port=8080
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
vector.store.name=networking-vector-store.json
logging.level.org.springframework.ai=DEBUG
spring.ai.openai.embedding.enabled=false
